### ISSUE TITLE
Error build on Xcode 11.1

### ISSUE THREAD

**Issue by abumuhammad-i** [AshampooSystems/boden#23]
..../boden/framework/foundation/platforms/foundationkit/filesystem/include/filesystem:291:8: Redefinition of '_FilesystemClock'

**Comment by gitoby** [comment]
Thanks for reporting.

I couldn't reproduce the issue. Which target did you try to build when the error occurred?

I just checked bodendemo on macOS Mojave and Catalina using Xcode 11.1 and it built successfully.

**Comment by gitoby** [comment]
Closing this as we didn't hear back from you. Please let us know if we can help.

**Comment by abumuhammad-i** [comment]
sorry just responded, I build Bodendemo on Xcode 11.1, and look error log here
<img width="803" alt="Screen Shot 2019-11-05 at 6 41 06 AM" src="https://user-images.githubusercontent.com/55430942/68167187-44260e00-ff97-11e9-8294-89fb56a7259d.png">

**Comment by Maddimax** [comment]
Try deleting the buildfolder and restart ./boden open. I've had similar issues when upgrading Xcode
